services:
  - type: web
    name: currency-converter
    runtime: java
    env: docker
    plan: free
    region: oregon
    buildCommand: "mvn clean package"
    startCommand: "java -jar target/currency-converter-1.0-SNAPSHOT.jar"