services:
  - type: web
    name: currency-converter
    runtime: java
    plan: free
    region: oregon
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/currency-converter-1.0-SNAPSHOT.jar"